//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace Trabalho.PubSubService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddorUpdateSubscriberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessagesByEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback TooggleSubscriberActiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubscriberByEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubscribersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmailListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveSubscribersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Trabalho.Properties.Settings.Default.Trabalho_PubSubService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddMessageCompletedEventHandler AddMessageCompleted;
        
        /// <remarks/>
        public event AddorUpdateSubscriberCompletedEventHandler AddorUpdateSubscriberCompleted;
        
        /// <remarks/>
        public event GetMessagesByEmailCompletedEventHandler GetMessagesByEmailCompleted;
        
        /// <remarks/>
        public event TooggleSubscriberActiveCompletedEventHandler TooggleSubscriberActiveCompleted;
        
        /// <remarks/>
        public event GetSubscriberByEmailCompletedEventHandler GetSubscriberByEmailCompleted;
        
        /// <remarks/>
        public event GetAllMessagesCompletedEventHandler GetAllMessagesCompleted;
        
        /// <remarks/>
        public event GetSubscribersCompletedEventHandler GetSubscribersCompleted;
        
        /// <remarks/>
        public event GetEmailListCompletedEventHandler GetEmailListCompleted;
        
        /// <remarks/>
        public event GetActiveSubscribersCompletedEventHandler GetActiveSubscribersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddMessage(string message, string email) {
            object[] results = this.Invoke("AddMessage", new object[] {
                        message,
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddMessageAsync(string message, string email) {
            this.AddMessageAsync(message, email, null);
        }
        
        /// <remarks/>
        public void AddMessageAsync(string message, string email, object userState) {
            if ((this.AddMessageOperationCompleted == null)) {
                this.AddMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMessageOperationCompleted);
            }
            this.InvokeAsync("AddMessage", new object[] {
                        message,
                        email}, this.AddMessageOperationCompleted, userState);
        }
        
        private void OnAddMessageOperationCompleted(object arg) {
            if ((this.AddMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMessageCompleted(this, new AddMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddorUpdateSubscriber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddorUpdateSubscriber(string name, string email, bool isActive) {
            object[] results = this.Invoke("AddorUpdateSubscriber", new object[] {
                        name,
                        email,
                        isActive});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddorUpdateSubscriberAsync(string name, string email, bool isActive) {
            this.AddorUpdateSubscriberAsync(name, email, isActive, null);
        }
        
        /// <remarks/>
        public void AddorUpdateSubscriberAsync(string name, string email, bool isActive, object userState) {
            if ((this.AddorUpdateSubscriberOperationCompleted == null)) {
                this.AddorUpdateSubscriberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddorUpdateSubscriberOperationCompleted);
            }
            this.InvokeAsync("AddorUpdateSubscriber", new object[] {
                        name,
                        email,
                        isActive}, this.AddorUpdateSubscriberOperationCompleted, userState);
        }
        
        private void OnAddorUpdateSubscriberOperationCompleted(object arg) {
            if ((this.AddorUpdateSubscriberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddorUpdateSubscriberCompleted(this, new AddorUpdateSubscriberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessagesByEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Publisher[] GetMessagesByEmail(string email) {
            object[] results = this.Invoke("GetMessagesByEmail", new object[] {
                        email});
            return ((Publisher[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMessagesByEmailAsync(string email) {
            this.GetMessagesByEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void GetMessagesByEmailAsync(string email, object userState) {
            if ((this.GetMessagesByEmailOperationCompleted == null)) {
                this.GetMessagesByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessagesByEmailOperationCompleted);
            }
            this.InvokeAsync("GetMessagesByEmail", new object[] {
                        email}, this.GetMessagesByEmailOperationCompleted, userState);
        }
        
        private void OnGetMessagesByEmailOperationCompleted(object arg) {
            if ((this.GetMessagesByEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessagesByEmailCompleted(this, new GetMessagesByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TooggleSubscriberActive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TooggleSubscriberActive(string email) {
            object[] results = this.Invoke("TooggleSubscriberActive", new object[] {
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TooggleSubscriberActiveAsync(string email) {
            this.TooggleSubscriberActiveAsync(email, null);
        }
        
        /// <remarks/>
        public void TooggleSubscriberActiveAsync(string email, object userState) {
            if ((this.TooggleSubscriberActiveOperationCompleted == null)) {
                this.TooggleSubscriberActiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTooggleSubscriberActiveOperationCompleted);
            }
            this.InvokeAsync("TooggleSubscriberActive", new object[] {
                        email}, this.TooggleSubscriberActiveOperationCompleted, userState);
        }
        
        private void OnTooggleSubscriberActiveOperationCompleted(object arg) {
            if ((this.TooggleSubscriberActiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TooggleSubscriberActiveCompleted(this, new TooggleSubscriberActiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubscriberByEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Subscriber GetSubscriberByEmail(string email) {
            object[] results = this.Invoke("GetSubscriberByEmail", new object[] {
                        email});
            return ((Subscriber)(results[0]));
        }
        
        /// <remarks/>
        public void GetSubscriberByEmailAsync(string email) {
            this.GetSubscriberByEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void GetSubscriberByEmailAsync(string email, object userState) {
            if ((this.GetSubscriberByEmailOperationCompleted == null)) {
                this.GetSubscriberByEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubscriberByEmailOperationCompleted);
            }
            this.InvokeAsync("GetSubscriberByEmail", new object[] {
                        email}, this.GetSubscriberByEmailOperationCompleted, userState);
        }
        
        private void OnGetSubscriberByEmailOperationCompleted(object arg) {
            if ((this.GetSubscriberByEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubscriberByEmailCompleted(this, new GetSubscriberByEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Publisher[] GetAllMessages() {
            object[] results = this.Invoke("GetAllMessages", new object[0]);
            return ((Publisher[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllMessagesAsync() {
            this.GetAllMessagesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllMessagesAsync(object userState) {
            if ((this.GetAllMessagesOperationCompleted == null)) {
                this.GetAllMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllMessagesOperationCompleted);
            }
            this.InvokeAsync("GetAllMessages", new object[0], this.GetAllMessagesOperationCompleted, userState);
        }
        
        private void OnGetAllMessagesOperationCompleted(object arg) {
            if ((this.GetAllMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllMessagesCompleted(this, new GetAllMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubscribers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Subscriber[] GetSubscribers() {
            object[] results = this.Invoke("GetSubscribers", new object[0]);
            return ((Subscriber[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSubscribersAsync() {
            this.GetSubscribersAsync(null);
        }
        
        /// <remarks/>
        public void GetSubscribersAsync(object userState) {
            if ((this.GetSubscribersOperationCompleted == null)) {
                this.GetSubscribersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubscribersOperationCompleted);
            }
            this.InvokeAsync("GetSubscribers", new object[0], this.GetSubscribersOperationCompleted, userState);
        }
        
        private void OnGetSubscribersOperationCompleted(object arg) {
            if ((this.GetSubscribersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubscribersCompleted(this, new GetSubscribersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmailList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmailList() {
            object[] results = this.Invoke("GetEmailList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmailListAsync() {
            this.GetEmailListAsync(null);
        }
        
        /// <remarks/>
        public void GetEmailListAsync(object userState) {
            if ((this.GetEmailListOperationCompleted == null)) {
                this.GetEmailListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmailListOperationCompleted);
            }
            this.InvokeAsync("GetEmailList", new object[0], this.GetEmailListOperationCompleted, userState);
        }
        
        private void OnGetEmailListOperationCompleted(object arg) {
            if ((this.GetEmailListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmailListCompleted(this, new GetEmailListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActiveSubscribers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Subscriber[] GetActiveSubscribers() {
            object[] results = this.Invoke("GetActiveSubscribers", new object[0]);
            return ((Subscriber[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveSubscribersAsync() {
            this.GetActiveSubscribersAsync(null);
        }
        
        /// <remarks/>
        public void GetActiveSubscribersAsync(object userState) {
            if ((this.GetActiveSubscribersOperationCompleted == null)) {
                this.GetActiveSubscribersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveSubscribersOperationCompleted);
            }
            this.InvokeAsync("GetActiveSubscribers", new object[0], this.GetActiveSubscribersOperationCompleted, userState);
        }
        
        private void OnGetActiveSubscribersOperationCompleted(object arg) {
            if ((this.GetActiveSubscribersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveSubscribersCompleted(this, new GetActiveSubscribersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Publisher {
        
        private int publisherIDField;
        
        private string subscriberEmailField;
        
        private Subscriber subscriberField;
        
        private string messageField;
        
        /// <remarks/>
        public int PublisherID {
            get {
                return this.publisherIDField;
            }
            set {
                this.publisherIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriberEmail {
            get {
                return this.subscriberEmailField;
            }
            set {
                this.subscriberEmailField = value;
            }
        }
        
        /// <remarks/>
        public Subscriber Subscriber {
            get {
                return this.subscriberField;
            }
            set {
                this.subscriberField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Subscriber {
        
        private string emailField;
        
        private string nameField;
        
        private bool isActiveField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AddMessageCompletedEventHandler(object sender, AddMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AddorUpdateSubscriberCompletedEventHandler(object sender, AddorUpdateSubscriberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddorUpdateSubscriberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddorUpdateSubscriberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessagesByEmailCompletedEventHandler(object sender, GetMessagesByEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessagesByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessagesByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Publisher[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Publisher[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TooggleSubscriberActiveCompletedEventHandler(object sender, TooggleSubscriberActiveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TooggleSubscriberActiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TooggleSubscriberActiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetSubscriberByEmailCompletedEventHandler(object sender, GetSubscriberByEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubscriberByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubscriberByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Subscriber Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Subscriber)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllMessagesCompletedEventHandler(object sender, GetAllMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Publisher[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Publisher[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetSubscribersCompletedEventHandler(object sender, GetSubscribersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubscribersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubscribersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Subscriber[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Subscriber[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetEmailListCompletedEventHandler(object sender, GetEmailListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmailListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmailListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetActiveSubscribersCompletedEventHandler(object sender, GetActiveSubscribersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveSubscribersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveSubscribersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Subscriber[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Subscriber[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591